version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - backend

  api:
    container_name: api
    image: node:lts-alpine
    restart: always
    volumes:
      - ./api-booking:/app
    working_dir: /app
    command: npm start
    env_file: ./api-booking/.env
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend: